### ISSUE TITLE
use ADCX instead of ADC in lowering of addcarry 

### ISSUE THREAD

**Issue by bgregoir** [jasmin-lang/jasmin#145]
Not sur it is important but this allows to not destroy the the other flags.

**Comment by tfaoliveira** [comment]
If I understand correctly, if we write `cf, a += b + cf;` it would get compiled to adcx instead of adc. 
ADCX and ADOX are defined in the context of the ADX extension, which is not supported by some older Intel CPUs (< 2014); For AMD CPUs I don't know the exact date. I have no strong feelings about this, but I suggest keeping it as it currently is.

**Comment by bgregoir** [comment]
Thank Tiago, 
   I think you are right we should not change this.
