### ISSUE TITLE
Non-trivial readme step

### ISSUE THREAD

**Issue by dsprenkels** [jasmin-lang/jasmin#7]
With cwd in `compiler/` the following `opam pin add -n jasmin .` command fails with this error:

```
Package jasmin does not exist, create as a NEW package? [Y/n] y
[jasmin.~dev] synchronised from file:///home/daan/jasmin/compiler
[WARNING] Failed checks on jasmin package definition from source at
          file:///home/daan/jasmin/compiler:
    error 57: Synopsis and description must not be both empty
jasmin is now pinned to file:///home/daan/jasmin/compiler (version 0.1)
```

cc @ildyria

**Comment by bgregoir** [comment]
Hi Daan, 
   I never use opam for jasmin.
   The easiest way to compile it for me is to use nix-shell
   once nix is installed go to your jasmin repo and do 
   > nix-shell
   > make 
Best regard, 
   Benjamin

**Comment by bgregoir** [comment]
I also encourage you to use the branch array_cast. 
It is more expressive.
B

**Comment by strub** [comment]
Still, if we have an invalid opam file, we should either fix it or remove it :)

I'm going to have a look.

**Comment by vbgl** [comment]
Dear Dann,

The message you’ve quoted says: “jasmin is now pinned”. This looks to me as a success rather than a command failure. Are you sure the command failed?

Also, if you are only interested in using the compiler, you may find there the OCaml sources freshly extracted (from the current state of the master branch): https://drop.infini.fr/r/OixbgV7yCI#aikwJECby0BIUdvihcSfC7PlWU7dupUZ2R0xTIvcgNs= You won’t need any Coq and Coq library to build it; only OCaml and a few common OCaml libraries (ocamlbuild, batteries, menhir and zarith).

That being said, it is true that how to get/build/run the jasmin compiler should be better documented.

**Comment by dsprenkels** [comment]
Now you mention it, the command did not fail, but only gave an error. A little context here is that @ildyria challenged me to do quick-and-dirty installation of jasmin, as a means to "test" the documentation.

**Comment by ildyria** [comment]
> Still, if we have an invalid opam file, we should either fix it or remove it :)

I'm in favor of fixing it. But it is just a personal preference (I use Opam more than Nix).

**Comment by wintersteiger** [comment]
+1, I get the same.

**Comment by vbgl** [comment]
The wrong README is gone, so this issue is no longer relevant.

Installation instructions have been moved to the [wiki](https://github.com/jasmin-lang/jasmin/wiki/Installation-instructions).
