### ISSUE TITLE
Assembler error Invalid pexpr for word

### ISSUE THREAD

**Issue by thornado123** [jasmin-lang/jasmin#9]
Hi Jasmin team

Im currently writing a fuzzer for the Jasmin compiler I haven't gotten it to crash yet but I've got this error message (and more like them):

compilation error in functions f0 and f0 at position line 14: assembler error Invalid pexpr for word
PLEASE REPORT

The source Jasmin code is auto generated. And line 14 is:

v6 +=(32123*((-(-v6))*32123)); 

I haven't been able to figure out if this way of assign a variable to itself is illegal in Jasmin or what?

Best regards Thor

**Comment by vbgl** [comment]
Hi. Thanks for your interest in Jasmin.

What assembler instruction to you expect the compiler to emit for this line?

I think it is expected that the compiler fails, but indeed, the error message should be improved.

**Comment by thornado123** [comment]
Sure! It is a nice framework. 
Im not sure to expect for that line haha but for something like v6 += v6 * 100 I would expect something like:  imul rax, rax, 101

**Comment by vbgl** [comment]
IMHO, programmers would be surprised if when they write “+” (aka, addition), they got a multiplication at assembly level.

Regarding LEA for addition with scaling, the compiler has the same restrictions as the underlying architecture: 1, 2, 4, and 8 are the only possible scales.

**Comment by thornado123** [comment]
Ohh thanks for clearing up the LEA part. I get your point but to me it seems like if z is allowed to be on the right hand side during a incrementation I would expect it to be allowed in an expression as well.

**Comment by bgregoir** [comment]
Hi,
Thanks for looking into Jasmin!
We will be very interested to hear about what you can find with your fuzzing approach.
However, please note that Jasmin has not be designed to be a general purpose language, so it has many limitations you will not find in other languages.
These are not checked by the front-end, and sometimes compilation just fails as a consequence of this.
Furthermore the error messages need clearly to be improved.
The error message you get is a typical example,  since we say « please report » while the entry code is clearly out of the scope of what we want for the jasmin compiler (where one source instruction should correspond to one assembly instruction).
Best regards,
Benjamin Grégoire

**Comment by thornado123** [comment]
Hi Benjamin and Vincent

Thanks for your time and clarifications. I get your points and I will send you a link to my report with my findings when it is done. 

Best regards Thor

**Comment by thornado123** [comment]
Oh Benjamin and Vincent

I have a one question about the compiler option -checksafety does it check for memory safety and constant time or how should it be understod? 

Best regards Thor

**Comment by vbgl** [comment]
Answers to these questions can now be found in the [wiki](https://github.com/jasmin-lang/jasmin/wiki/Safety-checker).

Quick answer: `-checksafety` infers sufficient preconditions on the inputs for memory safety & termination; constant-time verification is done by extraction to easycrypt of a suitable model and then safety verification of said model.
