### ISSUE TITLE
"type mismatch" after reg alloc

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#90]
I don't know if my program makes any sense, but compiling it gives an internal compilation error produced by the allocation checker after reg alloc.
```
export fn main () -> reg u64 {
  reg u64 res;
  reg u256 test;
  res = 0;
  ?{}, test = (256u) #ADD (res, res);
  res = (64u) test;
  return res;
}
```
```
"", line 1 (0) to line 8 (1):
internal compilation error in function main:
  Variable allocation: test (defined at line 3) and RAX (defined at line -1) : type mismatch
Please report at https://github.com/jasmin-lang/jasmin/issues
```

**Comment by eponier** [comment]
This even gives an assert false in the checker.

**Comment by vbgl** [comment]
Well spotted. There is at least a weird behavior in register-allocation: variables `res` (first argument of `#ADD_64`) and `test` (result of the same) are merged (due to architectural constraints) but they don’t have the same type. I guess that the error could be caught earlier but defending against this in regalloc seems sensible.
